language: node_js
node_js:
  - "0.12"
  - "iojs-v1.4.3"
  - "iojs-v1.5.1"
install:
  - npm install
  - npm install -g grunt-cli
  - sudo easy_install Pygments
  - 'echo "{}" > env.json'
  - mkdir logs
